language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
before_script:
- npm install -g gulp
script:
- gulp lint test
deploy:
  provider: npm
  email: lavrton@gmail.com
  api_key:
    secure: rYqyBhn3K8tnt/XK6RFodBiIsIqwmUuPBEAOQxRt/elK4F7BVC+ba7/xgsvdFLP+Bqn4sS8b/YjfxUqm0lfxoph3qvvyKZ+qjuGCXBtvbY8EgGqX3FJKq/LJp8Vu4encCUOpI3PWXQEB+0OrC8ntKnBn1L1WP6lzDbRHj49e9ew=
  on:
    tags: true
    all_branches: true
    repo: konvajs/konva
